### PR TITLE
fix: Identify and reject encrypted PDFs on upload

### PR DESCRIPTION
**Pull request by MangoS9**
# Description
According to code in the file helper file:

    File.open(filename) do |f|
     f.seek -4096, IO::SEEK_END unless f.size <= 4096
      f.read.include? '%%EOF'
    end
   
This code currently checks for the presence of '%%EOF' within the last 4096 bytes of the file. However, it lacks the capability to detect encrypted PDFs, which is why it proceeded with the procedure without raising any concerns. Before we proceed with the solution, let's discuss how we can identify an encrypted PDF.
image
When we open a PDF file using a text editor, we can spot the term '/Encrypted'. To effectively detect an encrypted PDF, our program needs to ensure that this term is absent from the file while it's being read.

**Before:**
image

**After:**
image

Video Demo:

https://github.com/thoth-tech/doubtfire-api/assets/128771372/2e89dc70-ca46-44bd-bfe6-0ed050fab6da

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Tested in Firefox
- [x] Using local encrypted PDF to upload on OnTrack

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Requested a review from seniors on the Pull Request

### CODE REVIEW

**Comment by maddernd** [comment]
Just looked at it again - reading the whole file into memory would be best to skip if we can


seek was good - to went to near the end of the file and read only the last 4kB

**Comment by MangoS9** [comment]
> Just looked at it again - reading the whole file into memory would be best to skip if we can
> 
> seek was good - to went to near the end of the file and read only the last 4kB

 The another way I can think of is iteration through bits and find the target but doubt that would really impact much of the performance

**Comment by maddernd** [comment]
If the encrypt is at the start - then scan part of the start for the text but no need to read all of the file into memory

**Comment by maddernd** [comment]
pending review from Andrew.

**Pull request closed without merging**
